# Generated by Django 5.2.8 on 2026-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('footwear', 'Footwear'), ('none', 'No Size')], default='none', max_length=20),
        ),
    ]
