# Generated by Django 5.2.8 on 2026-04-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_product_size_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('none', 'No Size'), ('clothing', 'Clothing'), ('footwear', 'Footwear')], default='none', max_length=20),
        ),
    ]
