# Generated by Django 5.2.8 on 2026-04-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_product_rating_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app1.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('footwear', 'Footwear'), ('none', 'No Size')], default='none', max_length=20),
        ),
    ]
