# Generated by Django 5.2.8 on 2026-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_product_rating_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('clothing', 'clothing'), ('footwear', 'Footwear'), ('none', 'No Size')], default='none', max_length=20),
        ),
    ]
